server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd
  flyway:
    locations: classpath:db/migration
    database: postgresql
    enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE
    org.springframework.jdbc: DEBUG
    org.springframework.data: DEBUG